services:
  # The Backend (PocketBase)
  pb_backend:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: ${COMPOSE_PROJECT_NAME}_pb
    restart: unless-stopped
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
    ports:
      - "${BACKEND_PORT}:8080"
    command:
      - serve
      - --http=0.0.0.0:8080
      - --dir=/pb_data
      - --migrationsDir=/pb_migrations

  # The Frontend (Next.js)
  frontend:
    build:
      context: ./reddot-frontend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=${NEXT_PUBLIC_POCKETBASE_URL}
      - POCKETBASE_INTERNAL_URL=${POCKETBASE_INTERNAL_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - pb_backend
